# Site settings
port: 4444
lang: en
title: Dr. Michel Combes's CV
description: Directeur Ingéniérie
favicon: /assets/img/favicon.png
photo: /assets/img/michel-circ1.png
#pdf: DrMichelCombes-CV.pdf
baseurl: "./"
url: https://michelc.tk/resumecard
rss_url: /pages/atom.xml
google_analytics: UA-63653234-1

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Michel Combes (PhD)
  title:
    fr: "Ingénieur Polymathique avec expérience"
    en: "Senior Polymathic Engineer"
  address: Ecublens, VD, Suisse
  phone: "+41 7676 0 9400"
  email: mgcombes@gmail.com
  link: http://linkedin.com/in/michel-combes
  weibo:
  github: michel47
  linkedin: mgc04
  twitter: mgcombes
  gavatar: /resumecard/assets/img/favicon.png
  stackoverflow:
